// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`API call should return error`] = `
Response {
  "size": 0,
  "timeout": 0,
  Symbol(Body internals): Object {
    "body": PassThrough {
      "_events": Object {
        "error": [Function],
        "prefinish": [Function],
      },
      "_eventsCount": 2,
      "_maxListeners": undefined,
      "_readableState": ReadableState {
        "autoDestroy": false,
        "awaitDrain": 0,
        "buffer": BufferList {
          "head": Object {
            "data": Object {
              "data": Array [
                79,
                111,
                112,
                115,
                33,
                32,
                84,
                104,
                101,
                32,
                115,
                101,
                114,
                118,
                101,
                114,
                32,
                101,
                114,
                114,
                111,
                114,
                101,
                100,
                32,
                194,
                175,
                92,
                95,
                40,
                227,
                131,
                132,
                41,
                95,
                47,
                194,
                175,
              ],
              "type": "Buffer",
            },
            "next": null,
          },
          "length": 1,
          "tail": Object {
            "data": Object {
              "data": Array [
                79,
                111,
                112,
                115,
                33,
                32,
                84,
                104,
                101,
                32,
                115,
                101,
                114,
                118,
                101,
                114,
                32,
                101,
                114,
                114,
                111,
                114,
                101,
                100,
                32,
                194,
                175,
                92,
                95,
                40,
                227,
                131,
                132,
                41,
                95,
                47,
                194,
                175,
              ],
              "type": "Buffer",
            },
            "next": null,
          },
        },
        "decoder": null,
        "defaultEncoding": "utf8",
        "destroyed": false,
        "emitClose": true,
        "emittedReadable": false,
        "encoding": null,
        "endEmitted": false,
        "ended": true,
        "flowing": null,
        "highWaterMark": 16384,
        "length": 38,
        "needReadable": false,
        "objectMode": false,
        "paused": true,
        "pipes": null,
        "pipesCount": 0,
        "readableListening": false,
        "reading": false,
        "readingMore": false,
        "resumeScheduled": false,
        "sync": false,
      },
      "_transformState": Object {
        "afterTransform": [Function],
        "needTransform": false,
        "transforming": false,
        "writecb": null,
        "writechunk": null,
        "writeencoding": "buffer",
      },
      "_writableState": WritableState {
        "autoDestroy": false,
        "bufferProcessing": false,
        "bufferedRequest": null,
        "bufferedRequestCount": 0,
        "corked": 0,
        "corkedRequestsFree": Object {
          "entry": null,
          "finish": [Function],
          "next": null,
        },
        "decodeStrings": true,
        "defaultEncoding": "utf8",
        "destroyed": false,
        "emitClose": true,
        "ended": true,
        "ending": true,
        "errorEmitted": false,
        "finalCalled": false,
        "finished": true,
        "highWaterMark": 16384,
        "lastBufferedRequest": null,
        "length": 0,
        "needDrain": false,
        "objectMode": false,
        "onwrite": [Function],
        "pendingcb": 0,
        "prefinished": true,
        "sync": false,
        "writecb": null,
        "writelen": 0,
        "writing": false,
      },
      "allowHalfOpen": true,
      "readable": true,
      "writable": false,
    },
    "disturbed": false,
    "error": null,
  },
  Symbol(Response internals): Object {
    "counter": 0,
    "headers": Headers {
      Symbol(map): Object {
        "connection": Array [
          "close",
        ],
        "content-length": Array [
          "38",
        ],
        "content-type": Array [
          "text/plain; charset=utf-8",
        ],
        "date": Array [
          "Wed, 19 Jun 2019 01:19:32 GMT",
        ],
        "server": Array [
          "Kestrel",
        ],
      },
    },
    "status": 500,
    "statusText": "Internal Server Error",
    "url": "https://pdqweb.azurewebsites.net/api/brain",
  },
}
`;
